import pandas as pd

df = pd.read_csv("ticket_dataset.csv")

df['Producto'] = df['Producto'].str.strip()
df['Producto'] = df['Producto'].str.upper()

df = df[df['Producto'] != 'PÀRQUING'] 

if 'Importe Total Ticket' in df.columns:
    df = df.drop(columns=['Importe Total Ticket'])

if 'Fecha' in df.columns:
    try:
        df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')
        df['Mes_Compra'] = df['Fecha'].dt.month
    except Exception as e:
        print(f"{e}")

product_categories = {
    'FRUTA Y VERDURA': ['BROCOLI', 'CEBA', 'TOMÀQUET', 'RAÏM', 'MELÓ', 'PRÉSSEC', 'CORS ROMANA', 'PATATA', 'PORROS', 'PINYA', 'PERA', 'ESPINACS', 'XAMPINYÓ', 'TARONJA', 'REMOLATXA', 'ICEBERG', 'GARROFÓ', 'TOM. RECEPTA ARTESAN', 'TOMATE ENSALADA BAND', 'FLOCS DE CIVADA'],  # Añadido FLOCS DE CIVADA
    'PANADERÍA Y BOLLERÍA': ['BAGUET', 'BOSSA PAPER', 'ROTLLE', 'PA HOT DOG', 'XAPATA', 'BARRA DE PA', 'MINIPANETS', 'BARRA CAMPEROLA', 'SOBAOS', 'MINI BURG', 'PA DE PESSIC', 'PA VIENA', 'NAPOLITANA', 'PA DE FORMATGE', 'GALETA'],  # Añadido GALETA (para GALETA FARCIDA CREMA)
    'LÁCTEOS Y HUEVOS': ['LLET', 'BÍFIDUS', 'FLAN QUESO', 'GREC NATURAL', 'NATA', 'BURRATA', 'MOZZARELLA', 'FORMATGE', 'FORMATGE FRESC', 'FORMATGE TALLS', 'FORMATGE RATLLAT', 'FORMATGE SEMI', 'FORMATGE FRESC AMANI', 'FORMATGE SANDWICH', 'PASTÍS FORMATGE', 'GOUDA'],  # Añadido GOUDA (para GOUDA SEMI RODANXES)
    'CHARCUTERÍA': ['ALLIOLI', 'PROT.', 'PERNIL', 'BOTIFARRA', 'CANSALADA', 'TALL PIT', 'LLONGANISSA', 'BOVÍ DAUS', 'LACON', 'ALES', 'FILET', 'PIT EXTRA T', 'LLONZA', 'SOBRASSADA', 'RULÓ CABRA', 'MORTADELA', 'PORCIONES BAC', 'MANDONGUILLES', 'FUET', 'TALL CAP DE LLOM', 'TALLS DE LLOM', 'SALSIT FRANKFURT'],
    'BEBIDAS': ['BEGUDA', 'CERVESA', 'CAFÈ', 'ALBARIÑO', 'VI', 'POWERADE', 'AQUARIUS', 'ISOTÓNICO', 'BEBER', 'AGUA', 'CERVES.SHANDY', 'TE', 'BEBIDA AVENA', 'CHOCO LECHE'],  # Añadido BEBIDA AVENA, CHOCO LECHE
    'LIMPIEZA Y HOGAR': ['BOSSA PLÀSTIC', 'PAPER HUMIT', 'BLANQUEJADOR', 'DESODORANT', 'HIGIÈNIC', 'NETEJADOR', 'GEL AMB LLEIXIU', 'DET.LI.', 'XAMPÚ', 'BOSSES ES.CUBELL', 'PAPER ALUMINI', 'FILM TRANSPARENT', 'SUAVITZANT', 'RECANVI LÍQUID INSEC', 'PARANYS ESCARABATS', 'DESEMBUSSADOR', 'DEO BODY SP', 'GEL FRESCOR', 'VIDRES MULTIUSOS', 'DET. BLANCA I COLOR', 'RECANVI TIRÀS', 'TIRÀS ATRAPAPOLS', 'FAIRY', 'ANTICALÇ', 'COLGATE', 'DESGREIXADOR'],  # Añadido DESGREIXADOR
    'CONSERVAS Y OTROS': ['BROU', 'SOPA', 'TONYINA', 'PRÉSSEC ALMÍV', 'MONGETA', 'OLI', 'OLIVA AMANIDA', 'FT MERLUZA', 'LLEIXIU NORMAL', 'PÈSOL', 'PULPIS', 'QUESO FRESCO'],  # Añadido QUESO FRESCO (para QUESO FRESCO ENSALAD)
    'PASTA Y ARROZ': ['FIDEU', 'FUSILLI', 'ARRÒS', 'GNOCCHI', 'LLENTIA', 'ANELLES BLAT', 'AROS DE MAÍZ', 'PUNTES SENSE GLUTEN'],
    'SNACKS Y GOLOSINAS': ['CARAMELS', 'CHEETOS', 'PALETS DE CRANC', 'CUQUITOS', 'CIVADA CRUNCHY', 'GOLOSINAS MINI MIX', 'NOU PACANA', 'PATATES BRAVES', 'CRUNCHY CHICKEN', 'FESTUC', 'CACAUET', 'BLAT MORO FREGIT', 'PATATES FREGIDES SAL', 'NUBI MALLOW'],  # Añadido NUBI MALLOW
    'CUIDADO PERSONAL': ['TAMPAX', 'COMP.', 'GEL COCO', 'CUIDACOL', 'DENTIFRICO', 'CR. MANOS HIDRATANTE', 'INTERDENTAL'],
    'PLATOS PREPARADOS': ['ROTI POLLASTRE', 'MAXI HAMBURGUESA', 'PIZZA CARBONARA', 'BENTO PEQUEÑO', 'POLLO TERIYAKI', 'CREMA CATALANA', 'COSTILLA CHURRASCO'],  # Añadido CREMA CATALANA, COSTILLA CHURRASCO
    'SALSAS Y ADEREZOS': ['ALLIOLI', 'SALSA BRAVA', 'SALSA CARBONARA'],
    'OTROS': ['AS. HERBES PROVENÇAL', 'VINAGRE BALSÀMIC', 'MELMELADA', 'BATUT XOCOLATA', 'TOTAL ACTION ELIX.', 'CAMAMILLA', 'NATA ESPRAI', 'COPA XOCOLATA', 'FILET PROVENÇAL', 'MEDALLONS GALL', 'FILTRES CAFÈ', 'BROQUETA', 'PRUNES', 'BURGER', 'MARGARINA', 'ESPELMES ANIVERSARI', 'ACOND REPARA', 'MORTADELA ACEITUNAS', 'COPOS DE AVENA', 'DET LIQ PRENDA DELIC', 'CHAMPÚ AC MENTOL', 'PISTACHO NATURAL', 'QUESO LONCHAS', 'CÁP. CLASSIC', 'PAPEL HUMEDO WC', 'BANDA CORTAR', 'APOSITO CLASSIC', 'PULGUITA', 'ROLLO HOGAR DOBLE', 'PASTÍS NATA-XOCOLATA', 'BATUT VAINILLA', 'NOCILLA', 'RIOJA CRIANÇA', 'BRAVAS', 'VALENCIANA', 'ENCENEDOR CUINA', 'AMETLLA MÒLTA', 'EL PESCAÍTO BLANCO', 'OLI V.EXTRA', 'FILET GALL', 'PIT GALL', 'CEREALS MIEL', 'VI RIOJA RESERVA', 'ESPRAI ROBA NETA', 'MEL DE FLORS', 'WOK POLLASTRE', 'GALL DINDI A DAUS', 'OLI VERGE EXTRA', 'MAGDALENA RODONA', 'CONTRACUIXA DESOSSAD', 'NATILLES VAINILLA', 'SAL FINA', 'AIGUA SENSE GAS', 'CÒCTEL NATURAL', 'SUCRE', 'FUZE TEA LLIMÓ LLAU.', 'CINTES DE BACÓ', 'AIGUA', 'PILOTETES', 'FORMATGE RATLLAT PIZ', 'MIG SALMÓ', 'DAUETS SALMÓ', 'BOSSA RÀFIA', 'F.TALLS EDAM TENDRE', 'CAFÉ G.AROMA MESCLA', 'PATATES SERRANO', 'FORMATGE SEMI TALLAT', 'BÍF FRUITES SIL', 'ENSALADILLA', 'COLGATE ANTICARIES', 'BIFRUITES TROPICAL', 'MAGDALENA SUCRE', 'PATATES XURRERIA', 'VACA TALLAT', 'FARINA DE CIGRÓ', 'CR. MANOS HIDRATANTE', 'FORMATGE TALLS SEMI', 'CARAMEL'] # Añadido CARAMEL (para CARAMEL EUCALIPTUS y CARAMEL REGALÈSIA)
}
def asignar_categoria(producto):
    producto = producto.upper()
    for categoria, palabras_clave in product_categories.items():
        for palabra in palabras_clave:
            if palabra in producto:
                return categoria
    return 'SIN CLASIFICAR'

df['Categoria_Producto'] = df['Producto'].apply(asignar_categoria)

df.to_csv('tickets_final.csv', index=False)